# Ce workflow se déclenche lors d'un push sur n'importe quelle branche
name: nom_custom_workflow

on:
  push:
    branches:
      - '*'  # Se déclenche sur toutes les branches

jobs:
  test:
    name: Exécuter les tests unitaires
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code (checkout)
        uses: actions/checkout@v3

      - name: Configurer Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Installer les dépendances (Maven)
        run: mvn install -DskipTests

      - name: Exécuter les tests unitaires
        run: mvn test
